# Generated by Django 5.0.4 on 2024-07-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prixAchat',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixVente',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qté',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
