# Generated by Django 5.0.4 on 2025-05-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
    ]
