# Generated by Django 5.0.4 on 2024-07-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_alter_produit_prixachat_alter_produit_prixvente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='prenom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='tel',
            field=models.CharField(default='0650378032', max_length=100),
            preserve_default=False,
        ),
    ]
