# Generated by Django 5.0.4 on 2024-07-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0003_users_prenom_users_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='qté',
            new_name='qte',
        ),
    ]
