# Generated by Django 5.0.4 on 2024-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_rename_qté_produit_qte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fournisseurs',
            },
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='adrFournisseur',
            new_name='codeBarre',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nomFournisseur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='telFourniseur',
        ),
    ]
