# Generated by Django 5.0.4 on 2025-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_auto_20250513_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemodel',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
