# Generated by Django 5.0.4 on 2025-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0005_commandemodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandemodel',
            name='test',
        ),
        migrations.AddField(
            model_name='commandemodel',
            name='statut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commandemodel',
            name='type_expedition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
