# Generated by Django 5.0.4 on 2024-07-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0005_fournisseur_rename_adrfournisseur_produit_codebarre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transcript.fournisseur'),
            preserve_default=False,
        ),
    ]
