# Generated by Django 5.0.4 on 2025-05-15 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0006_remove_commandemodel_test_commandemodel_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandemodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.clientmodel'),
        ),
        migrations.AlterField(
            model_name='commandemodel',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandemodel',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
