# Generated by Django 5.0.4 on 2025-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0007_alter_commandemodel_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandemodel',
            name='statut',
            field=models.CharField(blank=True, default='en cours de préparation', max_length=20, null=True),
        ),
    ]
