# Generated by Django 5.0.4 on 2025-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0008_alter_commandemodel_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemodel',
            name='numero_expéditeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commandemodel',
            name='statut',
            field=models.CharField(blank=True, default='En préparation', max_length=20, null=True),
        ),
    ]
