# Generated by Django 5.0.4 on 2024-07-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0009_alter_produit_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='qteMin',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
