# Generated by Django 5.0.4 on 2025-05-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0009_commandemodel_numero_expéditeur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandemodel',
            old_name='numero_expéditeur',
            new_name='numero_expediteur',
        ),
    ]
