# Generated by Django 5.0.4 on 2025-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0011_commandemodel_bordereau'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandemodel',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commandemodel',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commandemodel',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
