# Generated by Django 5.0.4 on 2025-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0012_commandemodel_adresse_commandemodel_code_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandemodel',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='commandemodel',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='commandemodel',
            name='ville',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
