# Generated by Django 4.2.13 on 2026-02-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0013_remove_commandemodel_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
