# Generated by Django 4.2.13 on 2026-03-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0016_alter_produit_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'associes',
            },
        ),
        migrations.CreateModel(
            name='MouvementCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_mvt', models.CharField(choices=[('injection', 'Injection'), ('retrait', 'Retrait')], default='injection', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_mvt', models.DateTimeField(auto_now_add=True)),
                ('associe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='transcript.associe')),
            ],
            options={
                'db_table': 'mouvements_capital',
                'ordering': ['-date_mvt'],
            },
        ),
    ]
