# Generated by Django 4.2.13 on 2026-03-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0017_associe_mouvementcapital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_bancaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'parametres_societe',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicules',
            },
        ),
        migrations.CreateModel(
            name='FraisVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='transcript.vehicule')),
            ],
            options={
                'db_table': 'frais_vehicules',
            },
        ),
    ]
