# Generated by Django 4.2.13 on 2026-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0018_parametressociete_vehicule_fraisvehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignetransaction',
            name='description_libre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvementcapital',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='mouvements/'),
        ),
    ]
