# Generated by Django 4.2.13 on 2026-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0019_document_mouvement_libre_ligne'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisGeneraux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket', models.FileField(blank=True, null=True, upload_to='frais/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'frais_generaux',
                'ordering': ['-date'],
            },
        ),
    ]
