# Generated by Django 4.2.13 on 2026-07-18 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0020_frais_generaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignetransaction',
            name='prix_achat_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lignetransaction',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcript.produit'),
        ),
    ]
