# Generated by Django 4.2.13 on 2026-07-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0022_backfill_prix_achat_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prixVenteGros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
